# Generated by Django 3.2 on 2023-12-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20231224_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'На рассмотрении'), ('APPROVED', 'Одобрено'), ('COMPLETED', 'Выполнено')], default='PENDING', max_length=20),
        ),
    ]
