# Generated by Django 3.2 on 2023-12-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('COMPLETED', 'COMPLETED')], default='PENDING', max_length=20),
        ),
    ]
