# Generated by Django 3.2 on 2023-12-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('шт', 'Штуки'), ('г', 'Граммы'), ('кг', 'Килограммы')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Нa расмотрении', 'PENDING'), ('Делается', 'APPROVED'), ('Доставлено', 'COMPLETED'), ('Отменено', 'CANCEL')], default='Нa расмотрении', max_length=20),
        ),
    ]
